name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum npm test
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: test-data/test.jar
    - uses: papeloto/action-zip@v1
      with:
        files: test-data/
        dest: test-result.zip
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: test-result.zip